"""empty message

Revision ID: 027ac4693fab
Revises: 76deb2ff6049
Create Date: 2022-02-19 19:48:44.102221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027ac4693fab'
down_revision = '76deb2ff6049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraps', sa.Column('colors', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraps', 'colors')
    # ### end Alembic commands ###
