"""empty message

Revision ID: 5feeb2e9e838
Revises: f288bd4242f8
Create Date: 2022-02-14 19:10:27.936496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5feeb2e9e838'
down_revision = 'f288bd4242f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraps', sa.Column('allergens', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraps', 'allergens')
    # ### end Alembic commands ###
