"""empty message

Revision ID: 76deb2ff6049
Revises: 2e0b5e16489c
Create Date: 2022-02-17 19:53:39.143247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76deb2ff6049'
down_revision = '2e0b5e16489c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'reply',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('likes_comment_id_fkey', 'likes', type_='foreignkey')
    op.drop_column('likes', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('likes_comment_id_fkey', 'likes', 'comments', ['comment_id'], ['id'])
    op.alter_column('comments', 'reply',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
