"""empty message

Revision ID: 2e0b5e16489c
Revises: 5528b7aa603c
Create Date: 2022-02-17 10:27:26.938478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0b5e16489c'
down_revision = '5528b7aa603c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reply', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'reply')
    # ### end Alembic commands ###
