"""empty message

Revision ID: 4753ce3031a1
Revises: 
Create Date: 2022-02-22 16:49:02.669334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4753ce3031a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('follows', 'following_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('follows', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('follows', 'following_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('follows', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
