"""empty message

Revision ID: e717ebb174fc
Revises: 55259de871ed
Create Date: 2022-02-25 18:04:31.324991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e717ebb174fc'
down_revision = '55259de871ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('conversation_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'conversation_name')
    # ### end Alembic commands ###
